### ISSUE TITLE
Inherit from `abc.ABC` instead of `abc.ABCMeta`

### ISSUE THREAD

**Issue by brettcannon** [brettcannon/knights-who-say-ni#15]
https://docs.python.org/3/library/abc.html#abc.ABC

**Comment by asvetlov** [comment]
Good finding, I totally forgot about `abc.ABC`.

**Comment by brettcannon** [comment]
Total luck I even noticed. :smile: I was actually looking for a way to tell what classes are registered with an ABC for a bug in importlib and happened to notice the new class.
