### ISSUE TITLE
Worry about redirects?

### ISSUE THREAD

**Issue by brettcannon** [brettcannon/knights-who-say-ni#16]
https://developer.github.com/v3/#parameters

Need to check if `aiohttp` will follow redirects automatically or not.

**Comment by asvetlov** [comment]
It does follow if `allow_redirects=True` (enabled by default), default `max_redirects=10` by default.
Actual code that performs redirections is here: https://github.com/KeepSafe/aiohttp/blob/master/aiohttp/client.py#L203

**Comment by asvetlov** [comment]
I believe you can close the issue.

**Comment by brettcannon** [comment]
Thanks for the info, @asvetlov !
